server:
  port: 8080

spring:
  application:
    name: backend

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: kyfo-backend

  prometheus:
    metrics:
      export:
        enabled: true
